DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS user;


CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE task (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	due_date DATE DEFAULT CURRENT_DATE,
	FOREIGN KEY (author_id) REFERENCES user (id)
);

